import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <div
          style={{
            backgroundImage: "url('/dashboardimg.jpg')",
            backgroundSize: "cover",
            height: "100vh",
            backgroundPosition: "center",
            backgroundRepeat: "no-repeat",
          }}
        > */}
          {children}
        {/* </div> */}
      </body>
    </html>
  );
}
